version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Zipping source files..."
      - zip -r lambda-package.zip app.py appspec.yml

artifacts:
  files:
    - lambda-package.zip
